sonar.projectKey=HumanPers0n702_Code
sonar.organization=humanpers0n702

# Name and version shown in SonarCloud UI
sonar.projectName=socket
sonar.projectVersion=1.0

# Point directly to your C source directory
sonar.sources=.

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Tell SonarCloud you want C/C++ analysis
sonar.language=c
